openapi: 3.0.1
info:
  title: backend
  version: '1.0'
paths:
  /WorldMap/GetAllContinents:
    get:
      tags:
        - WorldMap
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ContinentCollectionDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/ContinentCollectionDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/ContinentCollectionDTO'
  /WorldMap/GetCountriesFrom/{continentCode}/{limit}:
    get:
      tags:
        - WorldMap
      parameters:
        - name: continentCode
          in: path
          required: true
          style: simple
          schema:
            type: string
        - name: limit
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CountriesCollectionDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/CountriesCollectionDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/CountriesCollectionDTO'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ResponseMessageDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessageDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/ResponseMessageDTO'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ResponseMessageDTO'
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessageDTO'
            text/json:
              schema:
                $ref: '#/components/schemas/ResponseMessageDTO'
components:
  schemas:
    Continent:
      type: object
      properties:
        code:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
    ContinentCollectionDTO:
      type: object
      properties:
        continents:
          type: array
          items:
            $ref: '#/components/schemas/Continent'
          nullable: true
      additionalProperties: false
    CountriesCollectionDTO:
      type: object
      properties:
        countries:
          type: array
          items:
            $ref: '#/components/schemas/Country'
          nullable: true
      additionalProperties: false
    Country:
      type: object
      properties:
        code:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        currency:
          type: string
          nullable: true
        phone:
          type: string
          nullable: true
        languages:
          type: array
          items:
            $ref: '#/components/schemas/Language'
          nullable: true
        continent:
          $ref: '#/components/schemas/Continent'
      additionalProperties: false
    Language:
      type: object
      properties:
        name:
          type: string
          nullable: true
      additionalProperties: false
    ResponseMessageDTO:
      type: object
      properties:
        message:
          type: string
          nullable: true
      additionalProperties: false
